// ─── Branch Metadata ────────────────────────────────────────────────────────

export type BranchType =
  | "main"
  | "tangent"
  | "research"
  | "debug"
  | "docs"
  | "experiment";

// How the parent context is passed when this branch was created
export type ContextMode =
  | "full_context"   // full parent message history passed in
  | "summary";       // brancher generates a minimal context seed

export type NodeStatus =
  | "active"
  | "parked"         // summarized, stepped back to parent
  | "merged"         // summary injected into another node
  | "abandoned"      // explicitly closed without merging
  | "deprecated";    // superseded by a rollback branch

// ─── Message ────────────────────────────────────────────────────────────────

export type MessageRole = "system" | "user" | "assistant";

export interface Message {
  role: MessageRole;
  content: string;
  timestamp: string; // ISO
}

// ─── Tree Node ──────────────────────────────────────────────────────────────

export interface ConvoNode {
  id: string;                        // uuid
  parent_id: string | null;          // null = root
  branch_point_index: number | null; // index in parent.messages where we forked

  branch_type: BranchType;
  context_mode: ContextMode;
  status: NodeStatus;

  goal: string;                      // why this branch exists — set at creation
  context_seed: string | null;       // generated by Brancher when mode=summary
  messages: Message[];
  summary: string | null;            // generated by Summarizer on park/merge

  input_tokens: number;              // cumulative input tokens spent chatting in this node
  output_tokens: number;             // cumulative output tokens generated in this node

  created_at: string;
  updated_at: string;
}

// ─── Tree ───────────────────────────────────────────────────────────────────

export interface ConvoTree {
  id: string;
  name: string;
  root_node_id: string;
  active_node_id: string;
  created_at: string;
  updated_at: string;
}

// ─── LLM Provider Interface ─────────────────────────────────────────────────

export interface LLMMessage {
  role: "user" | "assistant";
  content: string;
}

export interface LLMResponse {
  content: string;
  usage?: {
    input_tokens: number;
    output_tokens: number;
    cache_read_input_tokens?: number;
    cache_creation_input_tokens?: number;
  };
}

// Per-call options. `cache` is only meaningful for multi-turn calls where the
// prefix is reused across turns (i.e. chat) — one-shot agent calls leave it off.
export interface CompleteOptions {
  cache?: boolean;     // enable prompt caching of the conversation prefix
  maxTokens?: number;  // override the client's configured max_tokens
  webSearch?: boolean; // enable provider server-side web search (Anthropic only)
}

export interface LLMClient {
  complete(
    messages: LLMMessage[],
    systemPrompt?: string,
    opts?: CompleteOptions
  ): Promise<LLMResponse>;
  provider: string;
  model: string;
}

// ─── Config ─────────────────────────────────────────────────────────────────

// Known providers keep autocomplete; the `(string & {})` arm allows any
// registered plugin provider (e.g. "ollama", "gemini") without a type edit.
export type LLMProvider = "anthropic" | "openai" | (string & {});

export interface Config {
  provider: LLMProvider;
  model: string;
  max_tokens: number;

  // Optional defaults for MCP folds — fall back to provider/model when unset.
  // Lets you run folds on a different model than the main chat (e.g. a cheaper
  // model). A per-fold `model`/`provider` tool argument overrides these.
  fold_provider?: string;
  fold_model?: string;

  api_keys: {
    anthropic?: string;
    openai?: string;
    [provider: string]: string | undefined;
  };
  db_path: string;
  default_context_mode: ContextMode;
}
